spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/submitappdb
    username: postgres
    password: admin
  jpa:
    hibernate:
      show-sql: true
      ddl-auto: validate
      sql: DEBUG
      type: TRACE
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yml

jwt:
  secret: slowdiveslowdiveslowdiveslowdiveslowdiveslowdiveslowdiveslowdiveslowdiveslowdiveslowdiveslowdiveslowdive
  expirationMs: 360000
