spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/submitappdb
    username: postgres
    password: admin
  jpa:
    properties:
      hibernate:
        show_sql: false
        ddl_auto: none
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yml