databaseChangeLog:
  - changeSet:
      id: 005
      author: Roman Vassilyev
      changes:
        - createTable:
            tableName: application
            columns:
              - column:
                  name: id
                  type: bigint
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: title
                  type: varchar(100)
                  constraints:
                    nullable: false
              - column:
                  name: text
                  type: text
                  constraints:
                    nullable: false
                    unique: true
              - column:
                  name: creation_time
                  type: timestamp with time zone
                  constraints:
                    nullable: false
              - column:
                  name: last_edit_time
                  type: timestamp with time zone
                  constraints:
                    nullable: false
              - column:
                  name: status_id
                  type: bigint
                  constraints:
                    nullable: false
              - column:
                  name: user_id
                  type: bigint
                  constraints:
                    nullable: false
        - createTable:
            tableName: status
            columns:
              - column:
                  name: id
                  type: bigint
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: name
                  type: varchar(50)
                  constraints:
                    unique: true
                    nullable: false
        - addForeignKeyConstraint:
            baseTableName: application
            baseColumnNames: status_id
            constraintName: STATUS_ID_FK_STATUS_CONSTRAINT
            deferrable: false
            initiallyDeferred: false
            referencedColumnNames: id
            referencedTableName: status
        - addForeignKeyConstraint:
            baseTableName: application
            baseColumnNames: user_id
            constraintName: USER_ID_FK_USER_CONSTRAINT
            deferrable: false
            initiallyDeferred: false
            referencedColumnNames: id
            referencedTableName: user_account